- README.markdown
- staff.md
Please peruse and merge - just some truncations of long gone staff..
> Some changes to staff

- projects/index.md
@mattben @pawpepe here are some typo corrections - we'll need to provide content for the new pages
> Typo tweaks

- about.md
@mattben @pawpepe @taylor13 some more tweaks
> Typo tweak and text replacement

- projects/index.md
Some additional tweaks and descriptive text
> Added further descriptive text for DandA and PMP

- software/index.html
> Added PMP and CF

- projects/index.md
@pawpepe @mattben there was a missing quote - fixed in this PR
> Fix missing quote in link

- about.md
@pawpepe this should fix the typo and participant list
> Further tweaks and typo fixes

- about.md
There appears to be another rogue `</div>` hanging around, so this *should* fix it
> Further cleanup - rogue /div

- projects/index.md
@taylor13 does this look right to you?
> Added Climate Model Diagnosis project

- staff.md
@pawpepe here is another addition
> Added jefferson9

- staff.md
@mattben the previous merge didn't follow the correct syntax - see http://pcmdi.github.io/staff.html
> syntax correction for jefferson9

- about/staff/nadeau/index.html
> Email link correction

- projects/4MIPs/index.html
> Edit to maintain consistency across projects

- projects/obs4MIPs/index.html
> title page correction

- README.markdown
> typo correction

- about/staff/sperber/index.html
> Title typo fix

- about/staff/celine/index.html
> Further title tweaks

- about/staff/curt/index.html
> title correction

- staff.md
@pawpepe @mattben another tweak
> Ji-Woo, Sasha phone number update

- about/staff/lee/index.html
@pawpepe @mattben another tweak
> Another fax number fix

- about/staff/sasha/index.html
@pawpepe one last merge, well a second last..
@mattben can you give me merge/admin privileges over this repo please?
> Update incorrect name

- about/staff/sperber/index.html
> Fix section formatting - Ken

- about/staff/nadeau/index.html
> Fix section formatting - Denis

- about/staff/angela/index.html
> Fix section formatting - Angela

- about/staff/curt/index.html
> Fix section formatting - Curt

- about/staff/celine/index.html
> Fix section formatting - Celine

- about/staff/sasha/index.html
> Fix section formatting

- CMIP6/CitationRequirements6-1.md
Added new CitationRequirements6-1.md file as per @taylor13 edits
> Update to CitationRequirements following @taylor13

- CMIP6/TermsOfUse/index.html
> Reconfigure CMIP6 terms of use info

- _includes/pcmdi_nav.html
- mips/index.md
- research/index.md
@mattben take a peek at this and if all looks good please merge
> Update navigation and overview landing pages

- Data/media/css/main.css
> Widen google search box

- research/researchHighlights.html
Resolves path issues for researchHighlights page
> Update path for page graphics

- _includes/hero.html
- _includes/pcmdi_nav.html
> Update nav to include esgf-node link

- CMIP6/Guide/index.md
@taylor13, starting the process it will require considerable iteration..
> First index.md pass

- CMIP6/Guide/dataManagers.md
- CMIP6/Guide/dataUsers.md
- CMIP6/Guide/index.md
- CMIP6/Guide/modelers.md
> Updates for modelers guide pages

- CMIP6/Guide/modelers.md
> Correct inplace http links

- CMIP6/Guide/modelers.md
> Correct link syntax

- CMIP6/Guide/modelers.md
> Fix italics

- CMIP6/Guide/modelers.md
> Update author list

- CMIP6/Guide/modelers.md
> Fix indent level

- projects/capt/publications.html
Further updating of publications.
> More updating of publications

- projects/capt/publications.html
1. deleted duplicated text for years 2016 and 2017
2. fixed hyperlink for Zhao et al. 2012
> two small changes

- staff/lee/index.html
> Update jiwoo's title

- CMIP6/Guide/modelers.md
>  DKRZ citation info updates @MartinaSt 

- Data/media/css/head.css
Here's an attempt at making the search bar look nicer.  #112
> Clean up google search box

- CMIP6/Guide/dataUsers.md
- CMIP6/index.md
Ready to commit.  Please check that link to new data stats table works.
> updated links

- mips/cmip5/guide.md
> Fix dead link to point to ES-DOC

- CMIP6/ArchiveStatistics/esgf_data_holdings/index.md
- CMIP6/ArchiveStatistics/esgf_data_holdings/print_view.html
> Add "print-friendly" view of ESGF CMIP6 data holdings tables

- CMIP6/Guide/dataManagers.md
> Update data managers guide

- CMIP6/Guide/index.md
> Update Guide page with Tables-of-contents to reflect new Data Manager's guide

- CMIP6/Guide/index.md
Karl and discussed and came up with a shortened list of items (14 was too many).
> Per discussion with KT, list shortened

- CMIP6/Guide/index.md
- CMIP6/index.md
Adding @glevava's map to the CMIP6 guide page
#263
> Add map of CMIP6 contributors to guide page

- CMIP6/index.md
> 263 embed cmip6 institution id map

- mips/amip/index.md
> Change registration link to mailto link for pcmdi-amipbcs mailing list

- CMIP6/index.md
Fix #263 
Adds updated map from @glevava.
Moves the center of the map to include all current locations in the iframe.
> Update CMIP Contributors map

- staff/durack/links/vanRenschetal19ClimDyn.html
- staff/durack/publication.html
> Update Durack publication page

- ipcc/diagnostic_subprojects.html
> Correct IPCC AR4 SPM link

- staff/durack/links/Marveletal19NAT.html
- staff/durack/publication.html
> Update Durack reflist for May 2019

- _includes/maintenance_banner.html
- _layouts/default.html
> Add maintenance banner for website outage on October 4-6, 2019.

- research/metrics/index_v1.3.0.md
- research/metrics/mean/plot_description_mean_clim_v1.3.1.md
@gleckler1 CMIP6 mean climate interative plot added.
@mauzey1 please merge, and could you please help this to be online ASAP? @gleckler1 needs this for his talk at 2pm today
> CMIP6 mean climate interative plot added

- research/metrics/enso/index.md
- research/metrics/index.md
- research/metrics/mean_clim/index.html
- research/metrics/mean_clim/index.md
- research/metrics/mjo/index.md
- research/metrics/monsoon/index.md
- research/metrics/variability_modes/index.md
by having index.md in each sub dirs.
> Use sub dir path as web address

- research/metrics/mean_clim/index.md
- research/metrics/mean_clim/pcmdiobs_info_dictionary_v2.0.json
- research/metrics/mean_clim/plot_description_mean_clim_v1.3.1.md
Update obs info prepared by @gleckler1.
@mauzey1 could you please merge? Thank you very much.
> mean clim update for obs

- _includes/pcmdi_nav.html
Fix #337 
@mauzey1 can you please review and merge
Ping @taylor13 @MartinaSt
> Update navigation CMIP6 guide links and text

- staff/durack/links/Riegeretal20GMD.html
> Durack publication page update March 2020

- staff/durack/links/UNChap5WOA21.html
- staff/durack/publication.html
@mauzey1 would you mind merging this
Ref #257
> Update Durack July 21

- staff/durack/links/UNChap4WOA16.html
Ref #257
@mauzey1 just caught another issue
> Correct Durack WOA I URL #257

- mips/cmip5/terms-of-use-old.md
- mips/cmip5/terms-of-use.md
Fix #421 
@taylor13 @matthew-mizielinski
> Update CMIP5 terms of reference

- mips/amip/index.md
Fix #428 
@mauzey1 please review and merge
> update for PCMDI-AMIP-1-1-7

- index.md
Close #440
@klein21 here are some tweaks over the top of your tweaks. @mauzey1 I was uncertain where to add the alt text, so haven't in this revised PR
> Further tweaks to klein21-master

- index.md
Ref #438
Ref #440 
Ref #441 
@mauzey1 @klein21 this should solve all the remaining issues
> catch further issues

- index.md
@mauzey1 I have made a pass at updating the graphic, using the png. Not sure whether my syntax is optimal, I am unfamiliar with the CSS templates and the outline/layout - please tweak as required and this should get us across the line for home page changes
> final tweaks; updated graphic

- _includes/pcmdi_nav.html
> update AMIP nav pages; add xCDAT link

- research/DandA/Synthetic Microwave Sounding Unit (MSU) temperatures/2017/Nature_Geoscience/index.md
- research/DandA/Synthetic Microwave Sounding Unit (MSU) temperatures/2018/hist_rcp85/index.md
- research/DandA/Synthetic Microwave Sounding Unit (MSU) temperatures/2018/index.md
- research/DandA/Synthetic Microwave Sounding Unit (MSU) temperatures/2018/piControl/index.md
- research/DandA/Synthetic Microwave Sounding Unit (MSU) temperatures/2018/satellite/index.md
> Add IM number for MSU data

- ipcc/standard_output.html
- ipcc/standard_output_updates.html
@taylor13 a fix as discussed
Fix #487 
@mauzey1 please merge when you get to it, this is a trivial typo fix
> #487 fix page title

- staff/Xie/index.md
Just made changes to my homepage
> Homepage Update

- _includes/pcmdi_nav.html
- research/index.md
- staff/index.md
Resolves #491 
Add changes to the site requested by @paullric.
Bo Dong is listed with a placeholder link.  This should be changed upon getting their contact info.
> Minor tweaks

- software/cmorTable/index.html
> update CMOR table page (#494)

- research/metrics/index.md
> Fix link to v1.5.1 evaluation page

- software/cmorTable/index.html
Fix #494 
@mauzey1 this fixes some inconsistent formatting, please review and merge when you can
> format update (#494)

- research/DandA/data.md
Adds link to data at https://pcmdi.llnl.gov/climate-data/PNAS_2023/Santer_MSU_SSU.zip
> Add entry and link for PNAS 2023 data on DandA data page

- staff/index.md
> Staff page update

- staff/index.md
@mauzey1 please review and merge when you get to it
@lee1043 if you get to it first?
> update staff list June 2023 (#507)

- staff/durack/links/Roethigetal23GCB.html
- staff/durack/links/Tesdaletal23JGR.html
- staff/durack/publication.html
Fix #515 
@mauzey1 would you mind reviewing and merging if this checks out?
> Durack July 2023 updates

- mips/obs4MIPs/index.html
- staff/taylor/karlcv.html
> Replace broken obs4MIPs link

- staff/durack/links/Dingleyetal23CMIP-IPO.html
- staff/durack/links/Hickmonetal22USDOE.html
- staff/durack/links/ORourkeetal23aCMIP-IPO.html
- staff/durack/links/ORourkeetal23bCMIP-IPO.html
- staff/durack/links/Schmidtetal23GFrontClim.html
- staff/durack/publication.html
> Durack Aug23 Updates #519

- CMIP6Plus/TermsOfUse/TermsOfUse6-5.md
- CMIP6Plus/TermsOfUse/index.html
Fix #530 
@mauzey1 please review and merge
> adding CMIP6Plus mip era ToU

- CMIP6Plus/TermsOfUse/TermsOfUse6-5.md
> adding @taylor13 tweaks

- CMIP6/index.html.forward
- CMIP6Plus/index.md
- _includes/pcmdi_nav.html
Ref #530 
@mauzey1 please review and merge when you're back from the break
> adding basic nav and default landing page CMIP6Plus

- software/ESGF/index.md
Fix #537
@mauzey1 please review and merge if suitable
@sashakames ping
> Add ESGF outage placeholder page

- staff/durack/links/Arcodiaetal23GRL.html
- staff/durack/links/CMIPPanel24CMIP-IPO.html
- staff/durack/links/Dunneetal23CMIP-IPO.html
- staff/durack/publication.html
> Durack Mar24 updates (#542)

- research/metrics/v1.6.2/variability_modes/index.md
- research/metrics/v1.6.2/variability_modes/taylordiagram/index.md
Fix broken links and recover page for variability modes Taylor diagrams
> Fix broken link and recover missed page

- research/metrics/v1.6.2/mjo/index.md
updating MJO interactive bar chart figure description for updated color palette. (Issue: https://github.com/PCMDI/PCMDI_Simulation_Summaries/issues/47)
> Update index.md for MJO figure description

- report/ab19.html
- report/ab70.html
- report/ab71.html
- report/report.html
Fix #548 
@mauzey1 please review and merge if no issues
> PCMDI Report fixes and updates

- staff/durack/links/Duracketal24CMIP6CVs.html
- staff/durack/links/Juckesetal24GMD.html
- staff/durack/links/Lambertetal24WIRES.html
- staff/durack/links/Tayloretal18CMIP6ModelMetadata.html
- staff/durack/publication.html
Fix #550 
@mauzey1 please review and merge if ok
> Issue550 durack1 august2024 update

- staff/durack/links/Arcodiaetal24JGR.html
- staff/durack/links/Mizielinskietal24CMIP-IPO.html
- staff/durack/publication.html
Fix #553 
@mauzey1 please review and merge if all is ok
> Durack update Sept24 (#553)

- _includes/pcmdi_nav.html
@mauzey1 can you review and merge please?
Are there any other overview/template instances that should be caught?
Fix #564
> update PCMDINav visual identity (#564)

- _includes/pcmdi_nav.html
- about.md
- location.md
- mips/input4MIPs/index.md
- research/index.md
- staff/durack/index.html
- staff/sperber/supplemental.html
> additional nav updates (#564)

- mips/input4MIPs/index.md
Fixes issue reported in https://github.com/PCMDI/pcmdi.github.io/pull/566#pullrequestreview-2625643250.
> Put URLs with curly braces within raw tags

- staff/durack/links/Dunneetal24GMD.html
- staff/durack/links/Duracketal25GMD.html
- staff/durack/links/Mizielinskietal24CMIP-IPO.html
- staff/durack/publication.html
Fix #570 
@mauzey1 please review and if all checks out, merge
> Durack Feb 2025 update (#570)

- staff/durack/publication.html
Caught a couple of errors in syntax
Ref #570
> syntax tweaks (#570)

- mips/input4MIPs/index.md
@mauzey1 another trivial tweak
Ref #564
> correcting link; augmenting content (#564)

- CMIP6Plus/TermsOfUse/TermsOfUse6-5.md
Address suggestions in #530 
Fix #530
> CMIP6Plus ToU update (#530)

- staff/index.md
@mauzey1 can you please review and merge?
Fix #575
> update project participants (#575)

- staff/durack/links/Arcodiaetal24JGR.html
- staff/durack/links/Arcodiaetal25JGR.html
- staff/durack/links/Lambertetal25WIRES.html
- staff/durack/links/Mauzeyetal24CMOR3.html
- staff/durack/links/Thierryetal25FrontiersMarSc.html
- staff/durack/publication.html
Fix #581 
@mauzey1 please review and merge if ok
> Durack April 2025 updates (#581)

- staff/durack/links/Durack22CEDA.html
- staff/durack/links/DurackTaylor16aESGF.html
- staff/durack/links/DurackTaylor16bESGF.html
- staff/durack/links/DurackTaylor17aESGF.html
- staff/durack/links/DurackTaylor17bESGF.html
- staff/durack/links/DurackWijffels11CSIRO.html
- staff/durack/links/Duracketal14CSIRO.html
- staff/durack/links/Duracketal25aESGF.html
- staff/durack/links/Duracketal25bESGF.html
- staff/durack/links/Duracketal25cESGF.html
- staff/durack/publication.html
Ref #589
@mauzey1 spotted some additional tweaks, and missing bits - if you can peruse and merge, no rush.
> More Durack Aug25 updates (#589)
